/// The default list of categories and shopping items. The values of the list are used to create
/// a default category data when a new account is created.
final categoryList = {
  "fruits": ["Apple", "Banana", "Cherry", "Date", "Grape", "Kiwi", "Lemon", "Mango", "Orange", "Pineapple"],
  "vegetables": [
    "Broccoli",
    "Carrot",
    "Spinach",
    "Lettuce",
    "Potato",
    "Tomato",
    "Onion",
    "Cabbage",
    "Cucumber",
    "Pepper"
  ],
  "beverages": ["Water", "Coffee", "Tea", "Soda", "Orange Juice", "Milk", "Lemonade", "Beer", "Wine", "Cocoa"],
  "meat": [
    "Chicken Breast",
    "Pork Chop",
    "Beef Steak",
    "Lamb Chop",
    "Turkey Slice",
    "Duck",
    "Bacon",
    "Sausage",
    "Ham",
    "Venison"
  ],
  "fish & seafood": ["Salmon", "Shrimp", "Tuna", "Mackerel", "Lobster", "Crab", "Oyster", "Clam", "Trout", "Cod"],
  "bakery": [
    "White Bread",
    "Croissant",
    "Bagel",
    "Muffin",
    "Donut",
    "Rye Bread",
    "Pita Bread",
    "Sourdough Loaf",
    "Danish Pastry",
    "Biscuit"
  ],
  "dairy & eggs": [
    "Milk",
    "Butter",
    "Cheese",
    "Yogurt",
    "Cream",
    "Ice Cream",
    "Eggs",
    "Cottage Cheese",
    "Sour Cream",
    "Whipped Cream"
  ],
  "froze": [
    "Frozen Pizza",
    "Frozen Vegetables",
    "Frozen Fruits",
    "Ice Cream",
    "Frozen Chicken Nuggets",
    "Frozen Fish Sticks",
    "Frozen Waffles",
    "Frozen Burrito",
    "Frozen French Fries",
    "Frozen Pie Crust"
  ],
  "pasta-rice & beans": [
    "Spaghetti",
    "Penne Pasta",
    "Rice",
    "Linguine",
    "Macaroni",
    "Black Beans",
    "Kidney Beans",
    "Lentils",
    "Chickpeas",
    "Basmati Rice"
  ],
  "canned foods": [
    "Canned Tuna",
    "Canned Tomatoes",
    "Canned Corn",
    "Canned Beans",
    "Canned Soup",
    "Canned Peaches",
    "Canned Green Beans",
    "Canned Pineapple",
    "Canned Chicken",
    "Canned Beef Stew"
  ],
  "deli & prepared food": [
    "Roasted Chicken",
    "Potato Salad",
    "Ham Sandwich",
    "Tuna Salad",
    "Macaroni Salad",
    "Stuffed Olives",
    "Grilled Vegetables",
    "Beef Wrap",
    "Sushi Roll",
    "Egg Salad"
  ],
  "sauces & condiments": [
    "Tomato Ketchup",
    "Mustard",
    "Soy Sauce",
    "Mayonnaise",
    "Hot Sauce",
    "BBQ Sauce",
    "Ranch Dressing",
    "Pickle Relish",
    "Worcestershire Sauce",
    "Teriyaki Sauce"
  ],
  "snacks": [
    "Potato Chips",
    "Pretzels",
    "Popcorn",
    "Trail Mix",
    "Granola Bar",
    "Chocolate Cookies",
    "Cheese Puffs",
    "Salted Nuts",
    "Fruit Gummies",
    "Rice Cakes"
  ],
  "baking & cooking": [
    "Flour",
    "Baking Powder",
    "Vanilla Extract",
    "Cocoa Powder",
    "Yeast",
    "Granulated Sugar",
    "Brown Sugar",
    "Baking Soda",
    "Cornstarch",
    "Olive Oil"
  ],
  "health & beauty": [
    "Shampoo",
    "Conditioner",
    "Toothpaste",
    "Facial Moisturizer",
    "Sunscreen",
    "Lip Balm",
    "Body Lotion",
    "Mascara",
    "Shaving Cream",
    "Vitamin C Tablets"
  ],
  "baby": [
    "Diapers",
    "Baby Wipes",
    "Baby Formula",
    "Baby Shampoo",
    "Teething Toy",
    "Pacifier",
    "Baby Food Jars",
    "Bottle Sterilizer",
    "Crib Sheets",
    "Stroller"
  ],
  "household": [
    "Laundry Detergent",
    "Dishwashing Soap",
    "All-purpose Cleaner",
    "Broom",
    "Mop",
    "Trash Bags",
    "Paper Towels",
    "Toilet Bowl Cleaner",
    "Sponges",
    "Window Cleaner"
  ],
  "pets": [
    "Dry Dog Food",
    "Cat Litter",
    "Parrot Seed Mix",
    "Fish Food Flakes",
    "Dog Collar",
    "Catnip Toy",
    "Aquarium Filter",
    "Dog Leash",
    "Bird Cage",
    "Cat Tree"
  ],
  "home & garden": [
    "Lawn Mower",
    "Flower Seeds",
    "Compost Bin",
    "Patio Furniture",
    "Garden Hose",
    "Indoor Plant Pot",
    "Fertilizer",
    "Weed Killer",
    "Gardening Gloves",
    "Landscape Lighting"
  ],
  "uncategorized": []
};
